/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.vtrabajador;
import Logica.ftrabajador;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daniel
 */
public class jfrmTrabajador extends javax.swing.JInternalFrame {

    /**
     * Creates new form jfrmCliente
     */
    public jfrmTrabajador() {
        initComponents();
        mostrar("");
        inhabilitar();
    }
    
    private String accion = "guardar";
    
    void ocultar_columnas(){
        tablaListaTrabajadores.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaListaTrabajadores.getColumnModel().getColumn(0).setMinWidth(0);
        tablaListaTrabajadores.getColumnModel().getColumn(0).setPreferredWidth(0);        
    } 
    
    void inhabilitar(){
        txtIdTrabajador.setVisible(false);
        txtApellidosTrabajador.setEnabled(false);
        txtNombreTrabajador.setEnabled(false);
        cboTipoDocTrabajador.setEnabled(false);
        txtNumeroDocTrabajador.setEnabled(false);
        txtDireccionTrabajador.setEnabled(false);
        txtTelefonoTrabajador.setEnabled(false);
        txtEmailTrabajador.setEnabled(false);
        
        txtSueldoTrabajador.setEnabled(false);
        cboAccesoTrabajador.setEnabled(false);
        txtLoginTrabajador.setEnabled(false);
        txtPasswordTrabajador.setEnabled(false);
        cboEstadoTrabajador.setEnabled(false);
        
        
        
       
        
        
        btnGuardarT.setEnabled(false);
        btnCancelarT.setEnabled(false);
        btnBorrarT.setEnabled(false);
        
        txtIdTrabajador.setText("");
        txtNombreTrabajador.setText("");
        txtApellidosTrabajador.setText("");
        
        
        cboTipoDocTrabajador.setSelectedItem("");
        txtNumeroDocTrabajador.setText("");
        txtDireccionTrabajador.setText("");
        txtTelefonoTrabajador.setText("");
        txtEmailTrabajador.setText("");
        txtSueldoTrabajador.setText("");
        cboAccesoTrabajador.setSelectedItem("");
        txtLoginTrabajador.setText("");
        txtPasswordTrabajador.setText("");
        cboEstadoTrabajador.setSelectedItem("");
    }
    
    void habilitar(){
        txtIdTrabajador.setVisible(true);
        txtApellidosTrabajador.setEnabled(true);
        txtNombreTrabajador.setEnabled(true);
        cboTipoDocTrabajador.setEnabled(true);
        txtNumeroDocTrabajador.setEnabled(true);
        txtDireccionTrabajador.setEnabled(true);
        txtTelefonoTrabajador.setEnabled(true);
        txtEmailTrabajador.setEnabled(true);
        txtSueldoTrabajador.setEnabled(true);
        cboAccesoTrabajador.setEnabled(true);
        txtLoginTrabajador.setEnabled(true);
        txtPasswordTrabajador.setEnabled(true);
        cboEstadoTrabajador.setEnabled(true);
        
        
        btnBorrarT.setEnabled(true);
        btnGuardarT.setEnabled(true);
        btnCancelarT.setEnabled(true);
        
        txtIdTrabajador.setText("");
        txtApellidosTrabajador.setText("");
        txtNombreTrabajador.setText("");
        
        
        cboTipoDocTrabajador.setSelectedItem("");
        txtNumeroDocTrabajador.setText("");
        txtDireccionTrabajador.setText("");
        txtTelefonoTrabajador.setText("");
        txtEmailTrabajador.setText("");
        txtSueldoTrabajador.setText("");
        cboAccesoTrabajador.setSelectedItem("");
        txtLoginTrabajador.setText("");
        txtPasswordTrabajador.setText("");
        cboEstadoTrabajador.setSelectedItem("");
        
    }
    
    void mostrar(String buscar){
        try {
            DefaultTableModel modelo;
            
            ftrabajador func = new ftrabajador();
            modelo = func.mostrar(buscar);
            tablaListaTrabajadores.setModel(modelo);
            
            ocultar_columnas();
            lblTotalRegistrosT.setText("Total Register: " + Integer.toString(func.totalRegistros));
            
            
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtIdTrabajador = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtApellidosTrabajador = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnGuardarT = new javax.swing.JButton();
        btnCancelarT = new javax.swing.JButton();
        btnNuevoT = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroDocTrabajador = new javax.swing.JTextField();
        cboTipoDocTrabajador = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtNombreTrabajador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTelefonoTrabajador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDireccionTrabajador = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmailTrabajador = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSueldoTrabajador = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtLoginTrabajador = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPasswordTrabajador = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cboAccesoTrabajador = new javax.swing.JComboBox<>();
        cboEstadoTrabajador = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtBuscarTrabajador = new javax.swing.JTextField();
        btnBuscarT = new javax.swing.JButton();
        btnBorrarT = new javax.swing.JButton();
        btnSalirT = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        tablaListaTrabajadores = new javax.swing.JTable();
        lblTotalRegistrosT = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBackground(java.awt.Color.orange);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel9.setText("Employee");

        jPanel4.setBackground(java.awt.Color.darkGray);
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registration of employees", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), java.awt.Color.white)); // NOI18N

        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("First Name:");

        txtApellidosTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosTrabajadorActionPerformed(evt);
            }
        });

        jLabel16.setForeground(java.awt.Color.white);
        jLabel16.setText("Type Doc:");

        btnGuardarT.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnGuardarT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/save.png"))); // NOI18N
        btnGuardarT.setText("SAVE");
        btnGuardarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTActionPerformed(evt);
            }
        });

        btnCancelarT.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnCancelarT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/delete.png"))); // NOI18N
        btnCancelarT.setText("CANCEL");

        btnNuevoT.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnNuevoT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/add.png"))); // NOI18N
        btnNuevoT.setText("NEW");
        btnNuevoT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoTActionPerformed(evt);
            }
        });

        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Num. Doc:");

        txtNumeroDocTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroDocTrabajadorActionPerformed(evt);
            }
        });

        cboTipoDocTrabajador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CI", "TP", "DNI", "TI", "NN", " " }));
        cboTipoDocTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoDocTrabajadorActionPerformed(evt);
            }
        });

        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setText("Last Name:");

        txtNombreTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreTrabajadorActionPerformed(evt);
            }
        });

        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("E-Mail:");

        txtTelefonoTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoTrabajadorActionPerformed(evt);
            }
        });

        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Phone:");

        txtDireccionTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionTrabajadorActionPerformed(evt);
            }
        });

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Address:");

        txtEmailTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailTrabajadorActionPerformed(evt);
            }
        });

        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Salary:");

        txtSueldoTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSueldoTrabajadorActionPerformed(evt);
            }
        });

        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Access:");

        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Login:");

        txtLoginTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginTrabajadorActionPerformed(evt);
            }
        });

        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("Password:");

        txtPasswordTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordTrabajadorActionPerformed(evt);
            }
        });

        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setText("State:");

        cboAccesoTrabajador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "TYPIST" }));

        cboEstadoTrabajador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "E", "D" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(txtApellidosTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombreTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtIdTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumeroDocTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDireccionTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboTipoDocTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel14))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmailTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefonoTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSueldoTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLoginTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPasswordTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboAccesoTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboEstadoTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNuevoT, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardarT, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelarT, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtIdTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(txtNombreTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(txtApellidosTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16))
                    .addComponent(cboTipoDocTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnNuevoT, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnGuardarT, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnCancelarT, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNumeroDocTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDireccionTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefonoTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtEmailTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtSueldoTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cboAccesoTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtLoginTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtPasswordTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(cboEstadoTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel7.setBackground(java.awt.Color.gray);
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "List employees", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), java.awt.Color.white)); // NOI18N

        jLabel20.setForeground(java.awt.Color.white);
        jLabel20.setText("Search:");

        btnBuscarT.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnBuscarT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/search.png"))); // NOI18N
        btnBuscarT.setText("SEARCH");
        btnBuscarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTActionPerformed(evt);
            }
        });

        btnBorrarT.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnBorrarT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/garbage.png"))); // NOI18N
        btnBorrarT.setText("TRASH");
        btnBorrarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarTActionPerformed(evt);
            }
        });

        btnSalirT.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        btnSalirT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/delete.png"))); // NOI18N
        btnSalirT.setText("QUIT");
        btnSalirT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirTActionPerformed(evt);
            }
        });

        tablaListaTrabajadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Type Doc", "Number Doc", "Address", "Phone", "E-Mail", "Salary", "Access", "Login", "Password", "State"
            }
        ));
        tablaListaTrabajadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaListaTrabajadoresMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(tablaListaTrabajadores);

        lblTotalRegistrosT.setForeground(java.awt.Color.red);
        lblTotalRegistrosT.setText("REGISTERS");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(txtBuscarTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarT)
                .addGap(18, 18, 18)
                .addComponent(btnBorrarT)
                .addGap(18, 18, 18)
                .addComponent(btnSalirT)
                .addGap(0, 24, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTotalRegistrosT))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane9)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtBuscarTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarT)
                    .addComponent(btnBorrarT)
                    .addComponent(btnSalirT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalRegistrosT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidosTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosTrabajadorActionPerformed
        // TODO add your handling code here:
        txtApellidosTrabajador.transferFocus();
    }//GEN-LAST:event_txtApellidosTrabajadorActionPerformed

    private void btnGuardarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTActionPerformed
        // TODO add your handling code here:
        //Validations
        
        
        if (txtNombreTrabajador.getText().length()==0) {
            JOptionPane.showConfirmDialog(rootPane, "Please enter first name of client");
            txtNombreTrabajador.requestFocus();
            return;
        }
        
        if (txtApellidosTrabajador.getText().length()==0) {
            JOptionPane.showConfirmDialog(rootPane, "Please enter last name of client");
            txtApellidosTrabajador.requestFocus();
            return;
        }

        if (txtNumeroDocTrabajador.getText().length()==0) {
            JOptionPane.showConfirmDialog(rootPane, "Please enter number doc. of client");
            txtNumeroDocTrabajador.requestFocus();
            return;
        }
        
        if (txtDireccionTrabajador.getText().length()==0) {
            JOptionPane.showConfirmDialog(rootPane, "Please enter address of client");
            txtDireccionTrabajador.requestFocus();
            return;
        }
        
        if (txtTelefonoTrabajador.getText().length()==0) {
            JOptionPane.showConfirmDialog(rootPane, "Please enter phone of client");
            txtTelefonoTrabajador.requestFocus();
            return;
        }
        
        if (txtEmailTrabajador.getText().length()==0) {
            JOptionPane.showConfirmDialog(rootPane, "Please enter email of client");
            txtEmailTrabajador.requestFocus();
            return;
        }
        
        if (txtSueldoTrabajador.getText().length()==0) {
            JOptionPane.showConfirmDialog(rootPane, "Please enter salary of client");
            txtSueldoTrabajador.requestFocus();
            return;
        }
        
        if (txtLoginTrabajador.getText().length()==0) {
            JOptionPane.showConfirmDialog(rootPane, "Please enter login of client");
            txtLoginTrabajador.requestFocus();
            return;
        }
        if (txtPasswordTrabajador.getText().length()==0) {
            JOptionPane.showConfirmDialog(rootPane, "Please enter password of client");
            txtPasswordTrabajador.requestFocus();
            return;
        }
        
        

        vtrabajador dts = new vtrabajador();
        ftrabajador func = new ftrabajador();

        dts.setNombre(txtNombreTrabajador.getText());
        dts.setApellidos(txtApellidosTrabajador.getText());
        int s = cboTipoDocTrabajador.getSelectedIndex();
        dts.setTipo_documento((String) cboTipoDocTrabajador.getItemAt(s));
        dts.setNum_documento(txtNumeroDocTrabajador.getText());
        dts.setDireccion(txtDireccionTrabajador.getText());
        dts.setTelefono(txtTelefonoTrabajador.getText());
        dts.setEmail(txtEmailTrabajador.getText());
        dts.setSueldo(Double.parseDouble(txtSueldoTrabajador.getText()));
        int s2 = cboAccesoTrabajador.getSelectedIndex();
        dts.setAcceso((String) cboAccesoTrabajador.getItemAt(s2));
        dts.setLogin(txtLoginTrabajador.getText());
        dts.setPassword(txtPasswordTrabajador.getText());
        int s3 = cboEstadoTrabajador.getSelectedIndex();
        dts.setEstado((String) cboEstadoTrabajador.getItemAt(s3));

        if (accion.equals("guardar")) {
            if (func.insertar(dts)) {
                JOptionPane.showMessageDialog(rootPane, "The client was registered successfully!");
                mostrar("");
                inhabilitar();
            }
        }else if(accion.equals("editar")){
            dts.setIdpersona(Integer.parseInt(txtIdTrabajador.getText()));

            if (func.editar(dts)) {
                JOptionPane.showMessageDialog(rootPane, "The client was edited successfully!");
                mostrar("");
                inhabilitar();
            }
        }
    }//GEN-LAST:event_btnGuardarTActionPerformed

    private void btnNuevoTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoTActionPerformed
        // TODO add your handling code here:
        habilitar();
        btnGuardarT.setText("Guardar");
        accion = "guardar";
    }//GEN-LAST:event_btnNuevoTActionPerformed

    private void cboTipoDocTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoDocTrabajadorActionPerformed
        // TODO add your handling code here:
        cboTipoDocTrabajador.transferFocus();
    }//GEN-LAST:event_cboTipoDocTrabajadorActionPerformed

    private void btnBuscarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTActionPerformed
        // TODO add your handling code here:
        mostrar(txtBuscarTrabajador.getText());
    }//GEN-LAST:event_btnBuscarTActionPerformed

    private void btnBorrarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTActionPerformed
        // TODO add your handling code here:
        if (!txtIdTrabajador.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Are you sure?","Comfirm",2);

            if (confirmacion==0) {
                ftrabajador func = new ftrabajador();
                vtrabajador dts = new vtrabajador();

                dts.setIdpersona(Integer.parseInt(txtIdTrabajador.getText()));
                func.eliminar(dts);
                mostrar("");
                inhabilitar();
            }
        }
    }//GEN-LAST:event_btnBorrarTActionPerformed

    private void btnSalirTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirTActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirTActionPerformed

    private void tablaListaTrabajadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaListaTrabajadoresMouseClicked
        // TODO add your handling code here:
        btnGuardarT.setText("EDIT");
        habilitar();
        btnBorrarT.setEnabled(true);
        accion = "editar";

        int fila = tablaListaTrabajadores.rowAtPoint(evt.getPoint());

        txtIdTrabajador.setText(tablaListaTrabajadores.getValueAt(fila, 0).toString());        
        txtNombreTrabajador.setText(tablaListaTrabajadores.getValueAt(fila, 1).toString());
        txtApellidosTrabajador.setText(tablaListaTrabajadores.getValueAt(fila, 2).toString());
        cboTipoDocTrabajador.setSelectedItem(tablaListaTrabajadores.getValueAt(fila, 3).toString());
        txtNumeroDocTrabajador.setText(tablaListaTrabajadores.getValueAt(fila, 4).toString());
        txtDireccionTrabajador.setText(tablaListaTrabajadores.getValueAt(fila, 5).toString());
        txtTelefonoTrabajador.setText(tablaListaTrabajadores.getValueAt(fila, 6).toString());
        txtEmailTrabajador.setText(tablaListaTrabajadores.getValueAt(fila, 7).toString());
        txtSueldoTrabajador.setText(tablaListaTrabajadores.getValueAt(fila, 8).toString());
        cboAccesoTrabajador.setSelectedItem(tablaListaTrabajadores.getValueAt(fila, 9).toString());
        txtLoginTrabajador.setText(tablaListaTrabajadores.getValueAt(fila, 10).toString());
        txtPasswordTrabajador.setText(tablaListaTrabajadores.getValueAt(fila, 11).toString());
        cboEstadoTrabajador.setSelectedItem(tablaListaTrabajadores.getValueAt(fila, 12).toString());

    }//GEN-LAST:event_tablaListaTrabajadoresMouseClicked

    private void txtNombreTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreTrabajadorActionPerformed
        // TODO add your handling code here:
        txtNombreTrabajador.transferFocus();
    }//GEN-LAST:event_txtNombreTrabajadorActionPerformed

    private void txtNumeroDocTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDocTrabajadorActionPerformed
        // TODO add your handling code here:
        txtNumeroDocTrabajador.transferFocus();
    }//GEN-LAST:event_txtNumeroDocTrabajadorActionPerformed

    private void txtDireccionTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionTrabajadorActionPerformed
        // TODO add your handling code here:
        txtDireccionTrabajador.transferFocus();
    }//GEN-LAST:event_txtDireccionTrabajadorActionPerformed

    private void txtTelefonoTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoTrabajadorActionPerformed
        // TODO add your handling code here:
        txtTelefonoTrabajador.transferFocus();
    }//GEN-LAST:event_txtTelefonoTrabajadorActionPerformed

    private void txtEmailTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailTrabajadorActionPerformed
        // TODO add your handling code here:
        txtEmailTrabajador.transferFocus();
    }//GEN-LAST:event_txtEmailTrabajadorActionPerformed

    private void txtSueldoTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSueldoTrabajadorActionPerformed
        // TODO add your handling code here:
        txtSueldoTrabajador.transferFocus();
    }//GEN-LAST:event_txtSueldoTrabajadorActionPerformed

    private void txtLoginTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginTrabajadorActionPerformed
        // TODO add your handling code here:
        txtLoginTrabajador.transferFocus();
    }//GEN-LAST:event_txtLoginTrabajadorActionPerformed

    private void txtPasswordTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordTrabajadorActionPerformed
        // TODO add your handling code here:
        txtPasswordTrabajador.transferFocus();
    }//GEN-LAST:event_txtPasswordTrabajadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmTrabajador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarT;
    private javax.swing.JButton btnBuscarT;
    private javax.swing.JButton btnCancelarT;
    private javax.swing.JButton btnGuardarT;
    private javax.swing.JButton btnNuevoT;
    private javax.swing.JButton btnSalirT;
    private javax.swing.JComboBox<String> cboAccesoTrabajador;
    private javax.swing.JComboBox<String> cboEstadoTrabajador;
    private javax.swing.JComboBox<String> cboTipoDocTrabajador;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblTotalRegistrosT;
    private javax.swing.JTable tablaListaTrabajadores;
    private javax.swing.JTextField txtApellidosTrabajador;
    private javax.swing.JTextField txtBuscarTrabajador;
    private javax.swing.JTextField txtDireccionTrabajador;
    private javax.swing.JTextField txtEmailTrabajador;
    private javax.swing.JTextField txtIdTrabajador;
    private javax.swing.JTextField txtLoginTrabajador;
    private javax.swing.JTextField txtNombreTrabajador;
    private javax.swing.JTextField txtNumeroDocTrabajador;
    private javax.swing.JTextField txtPasswordTrabajador;
    private javax.swing.JTextField txtSueldoTrabajador;
    private javax.swing.JTextField txtTelefonoTrabajador;
    // End of variables declaration//GEN-END:variables
}
