/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author daniel
 */
public class jfrmStart extends javax.swing.JFrame {

    /**
     * Creates new form jfrmStart
     */
    public jfrmStart() {
        initComponents();
        this.setExtendedState(jfrmStart.MAXIMIZED_BOTH);
        this.setTitle("Room reservation system and sales management - Manhattan Hotel");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEscritorio = new javax.swing.JDesktopPane();
        lblIdPersona = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblAcceso = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuSistemas = new javax.swing.JMenu();
        menuArchivos = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        menuReservaciones = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        menuConfiguraciones = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuHerramientas = new javax.swing.JMenu();
        menuAyuda = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelEscritorio.setBackground(java.awt.Color.gray);

        lblIdPersona.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblIdPersona.setText("jLabel1");
        panelEscritorio.add(lblIdPersona);
        lblIdPersona.setBounds(20, 30, 130, 18);

        lblNombre.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblNombre.setText("jLabel2");
        panelEscritorio.add(lblNombre);
        lblNombre.setBounds(20, 60, 130, 18);

        lblApellidos.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblApellidos.setText("jLabel3");
        panelEscritorio.add(lblApellidos);
        lblApellidos.setBounds(20, 90, 130, 18);

        lblAcceso.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblAcceso.setText("jLabel4");
        panelEscritorio.add(lblAcceso);
        lblAcceso.setBounds(20, 120, 130, 18);

        menuBar.setBackground(java.awt.Color.white);

        menuSistemas.setForeground(java.awt.Color.black);
        menuSistemas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/laptop.png"))); // NOI18N
        menuSistemas.setMnemonic('f');
        menuSistemas.setText("Systems");
        menuBar.add(menuSistemas);

        menuArchivos.setForeground(java.awt.Color.black);
        menuArchivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/profiles.png"))); // NOI18N
        menuArchivos.setMnemonic('e');
        menuArchivos.setText("Files");

        cutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        cutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/hotel.png"))); // NOI18N
        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Rooms");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        menuArchivos.add(cutMenuItem);

        copyMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        copyMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/monitor.png"))); // NOI18N
        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Products");
        copyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyMenuItemActionPerformed(evt);
            }
        });
        menuArchivos.add(copyMenuItem);

        menuBar.add(menuArchivos);

        menuReservaciones.setForeground(java.awt.Color.black);
        menuReservaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/booking.png"))); // NOI18N
        menuReservaciones.setMnemonic('h');
        menuReservaciones.setText("Reservations");

        contentMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        contentMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/time-left.png"))); // NOI18N
        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Reservations and Consumption");
        menuReservaciones.add(contentMenuItem);

        aboutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        aboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/conversation.png"))); // NOI18N
        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Clients");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        menuReservaciones.add(aboutMenuItem);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/credit-card.png"))); // NOI18N
        jMenuItem1.setText("Payments");
        menuReservaciones.add(jMenuItem1);

        menuBar.add(menuReservaciones);

        menuConsultas.setForeground(java.awt.Color.black);
        menuConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/business.png"))); // NOI18N
        menuConsultas.setText("Queries");
        menuBar.add(menuConsultas);

        menuConfiguraciones.setForeground(java.awt.Color.black);
        menuConfiguraciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/settings.png"))); // NOI18N
        menuConfiguraciones.setText("Configurations");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/hired.png"))); // NOI18N
        jMenuItem2.setText("Users and Access ");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuConfiguraciones.add(jMenuItem2);

        menuBar.add(menuConfiguraciones);

        menuHerramientas.setForeground(java.awt.Color.black);
        menuHerramientas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/tools.png"))); // NOI18N
        menuHerramientas.setText("Tools");
        menuBar.add(menuHerramientas);

        menuAyuda.setForeground(java.awt.Color.black);
        menuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/help.png"))); // NOI18N
        menuAyuda.setText("Help");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/website.png"))); // NOI18N
        jMenuItem3.setText("About As...");
        menuAyuda.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/technical-support.png"))); // NOI18N
        jMenuItem4.setText("Help");
        menuAyuda.add(jMenuItem4);

        menuBar.add(menuAyuda);

        menuSalir.setForeground(java.awt.Color.black);
        menuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/cancel.png"))); // NOI18N
        menuSalir.setText("Exit");
        menuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSalirMouseClicked(evt);
            }
        });
        menuBar.add(menuSalir);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        jfrmTrabajador frm = new jfrmTrabajador();
        panelEscritorio.add(frm);
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        // TODO add your handling code here:
        jfrmHabitacion frm = new jfrmHabitacion();
        panelEscritorio.add(frm);
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void copyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyMenuItemActionPerformed
        // TODO add your handling code here:
        jfrmProducto frm = new jfrmProducto();
        panelEscritorio.add(frm);
        frm.toFront();
        frm.setVisible(true);        
    }//GEN-LAST:event_copyMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
        jfrmCliente frm = new jfrmCliente();
        panelEscritorio.add(frm);
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void menuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSalirMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_menuSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmStart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    public static javax.swing.JLabel lblAcceso;
    public static javax.swing.JLabel lblApellidos;
    public static javax.swing.JLabel lblIdPersona;
    public static javax.swing.JLabel lblNombre;
    public static javax.swing.JMenu menuArchivos;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuBar menuBar;
    public static javax.swing.JMenu menuConfiguraciones;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenu menuHerramientas;
    private javax.swing.JMenu menuReservaciones;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JMenu menuSistemas;
    private javax.swing.JDesktopPane panelEscritorio;
    // End of variables declaration//GEN-END:variables

}
